### PR TITLE
Changed site styles

### PR DESCRIPTION
**Pull request by Alais29**
These are the changes I made:

- Changed font family to Montserrat for titles and Merriweather for the rest
- Changed font weight of titles to bold
- Changed font case to normal
- Changed navbar color to black
- Changed navbar items hover color
- Changed navbar button color
- Changed header background image
- Changed first section background color
- Changed footer social icons colors

I wanted to make some style changes to the form on the landing page too but I wasn't able to since the form is taking its styles from a cdn mailchimp stylesheet, It can be fixed by simply moving said stylesheet link to the "head" tag of the HTML file but I couldn't find the file which contains the head to make that change.

### CODE REVIEW

**Comment by JohannesLichtenberger** [comment]
Thank you so so much, I really love it :-)

The head is defined in https://github.com/sirixdb/sirixdb.github.io/blob/master/_includes/head.html

Oh and if you still like to, can we change the link colors, too (using either blue or this orange of the special Github button). I think then also the other pages fit quiet well with the new landing page layout, what do you think?

BTW: I had an error on Netlify, but I think I locally fixed it. Just would love to change the link colors, too :-) that said, I feel confident, that I can do it myself ;)

What do you think regarding the other pages? I think the only thing missing is some kind of a left navigation bar, where you can jump directly to sections and which doesn't scroll maybe :-)

Oh and regarding the landing page, instead of the stock-images maybe SVG graphics would be cool, but I'll have a look. Something like this: https://www.istockphoto.com/de/vektor/datenanalyse-gm1019917202-274054557

**Comment by JohannesLichtenberger** [comment]
Changed the link-color in the body to match the navigation bar dark blue :-) I like it

**Comment by Alais29** [comment]
Hi! I'm glad you liked it :) Regarding the head file, knowing where it is now, it should be easy enough to give some style to the form on the landing page, what do you say you give the task to @JoelLau who also commented on the issue on the other repository so he can contribute too? :) 

Regarding the other pages, I do think they fit quite well with the new style, maybe the left bar would be a good idea as you say, let me know what I can do about that this week and I'll let you know how it turns out.

About the SVG graphics, you mean to change the images on the POWERFUL APIS section? If you have the SVGs it should be an easy change to do too, let me know :)

**Comment by JohannesLichtenberger** [comment]
@JoelLau you like to work on this? 👍 

Currently I do not have the SVGs, but what do you think? I think SVG illustrations are somehow more beautiful... and more common nowadays probably? Yes, the POWERFUL APIS section. Guess I could change this easily myself, but would have to search a bit for fitting SVGs and then buy those :-)

**Comment by Alais29** [comment]
Yes I do think SVGs would probably look better on that part of the page :) Either way if you need any help adding them to the site, I'm happy to help 👍

**Comment by JohannesLichtenberger** [comment]
Maybe more help finding the right ones ;-)

**Comment by JohannesLichtenberger** [comment]
@Alais29 would you probably like to style the form? That would be awesome and I could create a new issue if it's for the #Hacktoberfest :-)

**Comment by JohannesLichtenberger** [comment]
Oh and regarding the SVG graphics, can I buy EPS files which can probably be converted to SVGs!?

**Comment by Alais29** [comment]
hi @JohannesLichtenberger I'm sorry I haven't been able to respond. I've been kinda busy this week too. Sure I can style the form, no problem :)

Regarding the graphics, I haven't worked with EPS files but I found some EPS to SVG file converters online so in theory, there shouldn't be any problem.

**Comment by JohannesLichtenberger** [comment]
Ah cool, thank you :-) if you know a good website where I can buy SVG graphics directly, that would also be great :-)

**Comment by Alais29** [comment]
I recently modified the form styles and made a pull request, please check it out when you can. 

About the svg graphics I wouldn't know the best site to get them, at my job the designer is the one in charge of getting the images and then he sends them to me so I can then build the site, maybe you could check shutterstock!

**Comment by JohannesLichtenberger** [comment]
Thank you so much, again :1st_place_medal:

**Pull request merged**
