### PR TITLE
fix:add extra lines to clarify the instruction

### PR DESCRIPTION
**Pull request by Aminmalek**

### CODE REVIEW

**Comment by Aminmalek** [comment]
@JohannesLichtenberger please review this

**Comment by JohannesLichtenberger** [comment]
Can you see my comments?

**Comment by Aminmalek** [comment]
> Can you see my comments?

no unfortunetly

**Comment by JohannesLichtenberger** [comment]
Screenshot from 2022-02-08 14-06-59

**Comment by JohannesLichtenberger** [comment]
Screenshot from 2022-02-08 14-06-59

**Comment by JohannesLichtenberger** [comment]
Screenshot from 2023-07-14 17-19-01

**Comment by Aminmalek** [comment]
@JohannesLichtenberger I fixed the issues

**Comment by JohannesLichtenberger** [comment]
Can you resolve the conflicts? Please update your branch :-)

**Comment by Aminmalek** [comment]
> Can you resolve the conflicts? Please update your branch :-)

Ok I will

**Pull request merged**
